version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.6
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - elasticsearch
    restart: unless-stopped
